### Add transaction
POST http://localhost:3000/transactions/add-transaction/224664222718
Content-Type: application/json

{
  "transactionId": "234555",
  "referenceId": "string",
  "externalId?": "string",
   "amount": 3000,
   "currency": "GNF",
   "payerPhone": "224787456783",
   "payerMessage": "message",
   "payerNote": "note",
   "status": "SUCCESSFUL",
   "failedReason": "raison",
   "transactionReason": "activationFee"
}
